<?xml version="1.0" encoding="utf-8"?><Database Name="Outin" Class="OutInDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ADOLFOROJAS\SQLEXPRESS;Initial Catalog=Outin;Integrated Security=True" SettingsObjectName="DataBase.Properties.Settings" SettingsPropertyName="OutinConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CambioCliente" Member="CambioCliente">
    <Type Name="CambioCliente">
      <Column Name="ca_idcambio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ca_idlista" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ca_movimientoinventario" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Association Name="ListaChequeo_CambioCliente" Member="ListaChequeo" ThisKey="ca_idlista" OtherKey="li_idlista" Type="ListaChequeo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Venta" Member="Venta">
    <Type Name="Venta">
      <Column Name="ve_idventa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ve_fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ve_cantidadproducto" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categoria" Member="Categoria">
    <Type Name="Categoria">
      <Column Name="cat_idcategoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cat_nombre" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Association Name="Categoria_Producto" Member="Producto" ThisKey="cat_idcategoria" OtherKey="pd_idcategoria" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.DanoDevolucion" Member="DanoDevolucion">
    <Type Name="DanoDevolucion">
      <Column Name="da_iddañodevolucion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="da_movimientoinventario" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="da_tipo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DetalleCompra" Member="DetalleCompra">
    <Type Name="DetalleCompra">
      <Column Name="dtl_idordencompra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dtl_cantidadproducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DetalleCompra_OrdenCompra" Member="OrdenCompra" ThisKey="dtl_idordencompra" OtherKey="or_detalle" Type="OrdenCompra" />
    </Type>
  </Table>
  <Table Name="dbo.Empleado" Member="Empleado">
    <Type Name="Empleado">
      <Column Name="em_identificacion" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="em_fechanacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="em_nombre" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="em_tipoid" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="em_direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="em_cargo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="em_contacto" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="em_fechaentrada" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="em_estado" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Empleado_MovimientoInventario" Member="MovimientoInventario" ThisKey="em_identificacion" OtherKey="mov_identificacionEmp" Type="MovimientoInventario" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Items">
      <Column Name="it_iditems" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="it_observacion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="it_texto" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="it_calificacion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Items_ListaChequeo" Member="ListaChequeo" ThisKey="it_iditems" OtherKey="li_iditems" Type="ListaChequeo" />
    </Type>
  </Table>
  <Table Name="dbo.ListaChequeo" Member="ListaChequeo">
    <Type Name="ListaChequeo">
      <Column Name="li_idlista" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="li_fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="li_iditems" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="li_serie" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="li_pregunta" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="li_calificacion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ListaChequeo_CambioCliente" Member="CambioCliente" ThisKey="li_idlista" OtherKey="ca_idlista" Type="CambioCliente" />
      <Association Name="ListaChequeo_OrdenCompra" Member="OrdenCompra" ThisKey="li_idlista" OtherKey="or_lista" Type="OrdenCompra" />
      <Association Name="Items_ListaChequeo" Member="Items" ThisKey="li_iditems" OtherKey="it_iditems" Type="Items" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MovimientoInventario" Member="MovimientoInventario">
    <Type Name="MovimientoInventario">
      <Column Name="mov_idmovimiento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mov_identificacionEmp" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="mov_idproducto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mov_idtipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mov_fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="mov_fechavencimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="mov_precioventa" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="mov_ubicacion" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="mov_preciocompra" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="mov_cantidadproductos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mov_total" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Empleado_MovimientoInventario" Member="Empleado" ThisKey="mov_identificacionEmp" OtherKey="em_identificacion" Type="Empleado" IsForeignKey="true" />
      <Association Name="Producto_MovimientoInventario" Member="Producto" ThisKey="mov_idproducto" OtherKey="pd_idproducto" Type="Producto" IsForeignKey="true" />
      <Association Name="Tipo_MovimientoInventario" Member="Tipo" ThisKey="mov_idtipo" OtherKey="ti_idtipo" Type="Tipo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdenCompra" Member="OrdenCompra">
    <Type Name="OrdenCompra">
      <Column Name="or_idordencompra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="or_detalle" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="or_lista" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="or_idproveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="or_fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="or_total" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="DetalleCompra_OrdenCompra" Member="DetalleCompra" ThisKey="or_detalle" OtherKey="dtl_idordencompra" Type="DetalleCompra" IsForeignKey="true" />
      <Association Name="ListaChequeo_OrdenCompra" Member="ListaChequeo" ThisKey="or_lista" OtherKey="li_idlista" Type="ListaChequeo" IsForeignKey="true" />
      <Association Name="Proveedor_OrdenCompra" Member="Proveedor" ThisKey="or_idproveedor" OtherKey="pro_idproveedor" Type="Proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="pd_idproducto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pd_nombre" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="pd_marca" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pd_stockmin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_stockmax" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_peso" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="pd_estado" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pd_idcategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Producto_MovimientoInventario" Member="MovimientoInventario" ThisKey="pd_idproducto" OtherKey="mov_idproducto" Type="MovimientoInventario" />
      <Association Name="Categoria_Producto" Member="Categoria" ThisKey="pd_idcategoria" OtherKey="cat_idcategoria" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Proveedor" Member="Proveedor">
    <Type Name="Proveedor">
      <Column Name="pro_idproveedor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pro_estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="pro_contacto" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="pro_direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pro_nombreempresa" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Association Name="Proveedor_OrdenCompra" Member="OrdenCompra" ThisKey="pro_idproveedor" OtherKey="or_idproveedor" Type="OrdenCompra" />
    </Type>
  </Table>
  <Table Name="dbo.Tipo" Member="Tipo">
    <Type Name="Tipo">
      <Column Name="ti_idtipo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ti_nombre" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="ti_descripcion" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Association Name="Tipo_MovimientoInventario" Member="MovimientoInventario" ThisKey="ti_idtipo" OtherKey="mov_idtipo" Type="MovimientoInventario" />
    </Type>
  </Table>
  <Function Name="dbo.insertarCambioCliente" Method="insertarCambioCliente">
    <Parameter Name="lista" Type="System.Int32" DbType="Int" />
    <Parameter Name="mov" Type="System.String" DbType="VarChar(60)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarTipo" Method="modificarTipo">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarCategoria" Method="insertarCategoria">
    <Parameter Name="nom" Type="System.String" DbType="VarChar(70)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarDañoDevolucion" Method="insertarDañoDevolucion">
    <Parameter Name="mov" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="tipo" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarDetalleCompra" Method="insertarDetalleCompra">
    <Parameter Name="cant" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarEmpleado" Method="insertarEmpleado">
    <Parameter Name="nacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="tipo" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="dir" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cargo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="contacto" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="entrada" Type="System.DateTime" DbType="Date" />
    <Parameter Name="estado" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarListaChequeo" Method="insertarListaChequeo">
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="items" Type="System.Int32" DbType="Int" />
    <Parameter Name="serie" Type="System.Int32" DbType="Int" />
    <Parameter Name="pregunta" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="calificacion" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarMoviInventario" Method="insertarMoviInventario">
    <Parameter Name="identificacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="producto" Type="System.Int32" DbType="Int" />
    <Parameter Name="tipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="fechaVenc" Type="System.DateTime" DbType="Date" />
    <Parameter Name="precioVenta" Type="System.Decimal" DbType="Money" />
    <Parameter Name="ubicacion" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="precioCompra" Type="System.Decimal" DbType="Money" />
    <Parameter Name="cantProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="total" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarOrdenCompra" Method="insertarOrdenCompra">
    <Parameter Name="detalle" Type="System.Int32" DbType="Int" />
    <Parameter Name="lista" Type="System.Int32" DbType="Int" />
    <Parameter Name="proveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="total" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarProducto" Method="insertarProducto">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="marca" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="stockMin" Type="System.Int32" DbType="Int" />
    <Parameter Name="stockMax" Type="System.Int32" DbType="Int" />
    <Parameter Name="peso" Type="System.Double" DbType="Float" />
    <Parameter Name="estado" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="categoria" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarProveedor" Method="insertarProveedor">
    <Parameter Name="estado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="contacto" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="nomEmpresa" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarTipo" Method="insertarTipo">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarVenta" Method="insertarVenta">
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insetarItems" Method="insetarItems">
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="texto" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="calificacion" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modficarVenta" Method="modficarVenta">
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarCambioCliente" Method="modificarCambioCliente">
    <Parameter Name="lista" Type="System.Int32" DbType="Int" />
    <Parameter Name="mov" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarCategoria" Method="modificarCategoria">
    <Parameter Name="nom" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarDañoDevolucion" Method="modificarDañoDevolucion">
    <Parameter Name="mov" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="tipo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarDetalleCompra" Method="modificarDetalleCompra">
    <Parameter Name="cant" Type="System.Int32" DbType="Int" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarEmpleado" Method="modificarEmpleado">
    <Parameter Name="nacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="tipo" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="dir" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cargo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="contacto" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="entrada" Type="System.DateTime" DbType="Date" />
    <Parameter Name="estado" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="id" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarItems" Method="modificarItems">
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="texto" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="calificacion" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarListaChequeo" Method="modificarListaChequeo">
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="items" Type="System.Int32" DbType="Int" />
    <Parameter Name="serie" Type="System.Int32" DbType="Int" />
    <Parameter Name="pregunta" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="calificacion" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarMoviInventario" Method="modificarMoviInventario">
    <Parameter Name="identificacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="producto" Type="System.Int32" DbType="Int" />
    <Parameter Name="tipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="fechaVenc" Type="System.DateTime" DbType="Date" />
    <Parameter Name="precioVenta" Type="System.Decimal" DbType="Money" />
    <Parameter Name="ubicacion" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="precioCompra" Type="System.Decimal" DbType="Money" />
    <Parameter Name="cantProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="total" Type="System.Decimal" DbType="Money" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarOrdenCompra" Method="modificarOrdenCompra">
    <Parameter Name="detalle" Type="System.Int32" DbType="Int" />
    <Parameter Name="lista" Type="System.Int32" DbType="Int" />
    <Parameter Name="proveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="total" Type="System.Decimal" DbType="Money" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarProducto" Method="modificarProducto">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="marca" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="stockMin" Type="System.Int32" DbType="Int" />
    <Parameter Name="stockMax" Type="System.Int32" DbType="Int" />
    <Parameter Name="peso" Type="System.Double" DbType="Float" />
    <Parameter Name="estado" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="categoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.modificarProveedor" Method="modificarProveedor">
    <Parameter Name="estado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="contacto" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="nomEmpresa" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>