#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Outin")]
	public partial class OutInDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCambioCliente(CambioCliente instance);
    partial void UpdateCambioCliente(CambioCliente instance);
    partial void DeleteCambioCliente(CambioCliente instance);
    partial void InsertVenta(Venta instance);
    partial void UpdateVenta(Venta instance);
    partial void DeleteVenta(Venta instance);
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertDanoDevolucion(DanoDevolucion instance);
    partial void UpdateDanoDevolucion(DanoDevolucion instance);
    partial void DeleteDanoDevolucion(DanoDevolucion instance);
    partial void InsertDetalleCompra(DetalleCompra instance);
    partial void UpdateDetalleCompra(DetalleCompra instance);
    partial void DeleteDetalleCompra(DetalleCompra instance);
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    partial void InsertItems(Items instance);
    partial void UpdateItems(Items instance);
    partial void DeleteItems(Items instance);
    partial void InsertListaChequeo(ListaChequeo instance);
    partial void UpdateListaChequeo(ListaChequeo instance);
    partial void DeleteListaChequeo(ListaChequeo instance);
    partial void InsertMovimientoInventario(MovimientoInventario instance);
    partial void UpdateMovimientoInventario(MovimientoInventario instance);
    partial void DeleteMovimientoInventario(MovimientoInventario instance);
    partial void InsertOrdenCompra(OrdenCompra instance);
    partial void UpdateOrdenCompra(OrdenCompra instance);
    partial void DeleteOrdenCompra(OrdenCompra instance);
    partial void InsertProveedor(Proveedor instance);
    partial void UpdateProveedor(Proveedor instance);
    partial void DeleteProveedor(Proveedor instance);
    partial void InsertTipo(Tipo instance);
    partial void UpdateTipo(Tipo instance);
    partial void DeleteTipo(Tipo instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    #endregion
		
		public OutInDBDataContext() : 
				base(global::DataBase.Properties.Settings.Default.OutinConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CambioCliente> CambioCliente
		{
			get
			{
				return this.GetTable<CambioCliente>();
			}
		}
		
		public System.Data.Linq.Table<Venta> Venta
		{
			get
			{
				return this.GetTable<Venta>();
			}
		}
		
		public System.Data.Linq.Table<Categoria> Categoria
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<DanoDevolucion> DanoDevolucion
		{
			get
			{
				return this.GetTable<DanoDevolucion>();
			}
		}
		
		public System.Data.Linq.Table<DetalleCompra> DetalleCompra
		{
			get
			{
				return this.GetTable<DetalleCompra>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleado
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<Items> Items
		{
			get
			{
				return this.GetTable<Items>();
			}
		}
		
		public System.Data.Linq.Table<ListaChequeo> ListaChequeo
		{
			get
			{
				return this.GetTable<ListaChequeo>();
			}
		}
		
		public System.Data.Linq.Table<MovimientoInventario> MovimientoInventario
		{
			get
			{
				return this.GetTable<MovimientoInventario>();
			}
		}
		
		public System.Data.Linq.Table<OrdenCompra> OrdenCompra
		{
			get
			{
				return this.GetTable<OrdenCompra>();
			}
		}
		
		public System.Data.Linq.Table<Proveedor> Proveedor
		{
			get
			{
				return this.GetTable<Proveedor>();
			}
		}
		
		public System.Data.Linq.Table<Tipo> Tipo
		{
			get
			{
				return this.GetTable<Tipo>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarCambioCliente")]
		public int insertarCambioCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lista, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string mov)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lista, mov);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insetarItems")]
		public int insetarItems([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string observacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string texto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> calificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), observacion, texto, calificacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarCategoria")]
		public int insertarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(70)")] string nom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarDañoDevolucion")]
		public int insertarDañoDevolucion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string mov, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mov, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarDetalleCompra")]
		public int insertarDetalleCompra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cant)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cant);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarListaChequeo")]
		public int insertarListaChequeo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> items, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> serie, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string pregunta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> calificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha, items, serie, pregunta, calificacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarMoviInventario")]
		public int insertarMoviInventario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> identificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> producto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaVenc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string ubicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), identificacion, producto, tipo, fecha, fechaVenc, ubicacion, cantidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarOrdenCompra")]
		public int insertarOrdenCompra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> detalle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lista, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> proveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> total)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), detalle, lista, proveedor, fecha, total);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarProveedor")]
		public int insertarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> contacto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(70)")] string nomEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), estado, contacto, direccion, nomEmpresa, id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarTipo")]
		public int insertarTipo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, descripcion, id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarVenta")]
		public int insertarVenta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha, cantidad, id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.validarUsuario")]
		public ISingleResult<validarUsuarioResult> validarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contrasena);
			return ((ISingleResult<validarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarEmpleado")]
		public int insertarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> nacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(70)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dir, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cargo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string contacto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> entrada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nacimiento, nombre, contrasena, tipo, dir, cargo, contacto, entrada, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarEmpleado")]
		public ISingleResult<listarEmpleadoResult> listarEmpleado()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarEmpleadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarProducto")]
		public int insertarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(70)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string marca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stockMin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stockMax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> peso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> preCompra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> preVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cant, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> categoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, marca, stockMin, stockMax, peso, preCompra, preVenta, estado, cant, categoria);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CambioCliente")]
	public partial class CambioCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ca_idcambio;
		
		private System.Nullable<int> _ca_idlista;
		
		private string _ca_movimientoinventario;
		
		private EntityRef<ListaChequeo> _ListaChequeo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onca_idcambioChanging(int value);
    partial void Onca_idcambioChanged();
    partial void Onca_idlistaChanging(System.Nullable<int> value);
    partial void Onca_idlistaChanged();
    partial void Onca_movimientoinventarioChanging(string value);
    partial void Onca_movimientoinventarioChanged();
    #endregion
		
		public CambioCliente()
		{
			this._ListaChequeo = default(EntityRef<ListaChequeo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ca_idcambio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ca_idcambio
		{
			get
			{
				return this._ca_idcambio;
			}
			set
			{
				if ((this._ca_idcambio != value))
				{
					this.Onca_idcambioChanging(value);
					this.SendPropertyChanging();
					this._ca_idcambio = value;
					this.SendPropertyChanged("ca_idcambio");
					this.Onca_idcambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ca_idlista", DbType="Int")]
		public System.Nullable<int> ca_idlista
		{
			get
			{
				return this._ca_idlista;
			}
			set
			{
				if ((this._ca_idlista != value))
				{
					if (this._ListaChequeo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onca_idlistaChanging(value);
					this.SendPropertyChanging();
					this._ca_idlista = value;
					this.SendPropertyChanged("ca_idlista");
					this.Onca_idlistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ca_movimientoinventario", DbType="VarChar(60)")]
		public string ca_movimientoinventario
		{
			get
			{
				return this._ca_movimientoinventario;
			}
			set
			{
				if ((this._ca_movimientoinventario != value))
				{
					this.Onca_movimientoinventarioChanging(value);
					this.SendPropertyChanging();
					this._ca_movimientoinventario = value;
					this.SendPropertyChanged("ca_movimientoinventario");
					this.Onca_movimientoinventarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ListaChequeo_CambioCliente", Storage="_ListaChequeo", ThisKey="ca_idlista", OtherKey="li_idlista", IsForeignKey=true)]
		public ListaChequeo ListaChequeo
		{
			get
			{
				return this._ListaChequeo.Entity;
			}
			set
			{
				ListaChequeo previousValue = this._ListaChequeo.Entity;
				if (((previousValue != value) 
							|| (this._ListaChequeo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ListaChequeo.Entity = null;
						previousValue.CambioCliente.Remove(this);
					}
					this._ListaChequeo.Entity = value;
					if ((value != null))
					{
						value.CambioCliente.Add(this);
						this._ca_idlista = value.li_idlista;
					}
					else
					{
						this._ca_idlista = default(Nullable<int>);
					}
					this.SendPropertyChanged("ListaChequeo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Venta")]
	public partial class Venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ve_idventa;
		
		private System.DateTime _ve_fecha;
		
		private System.Nullable<int> _ve_cantidadproducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onve_idventaChanging(int value);
    partial void Onve_idventaChanged();
    partial void Onve_fechaChanging(System.DateTime value);
    partial void Onve_fechaChanged();
    partial void Onve_cantidadproductoChanging(System.Nullable<int> value);
    partial void Onve_cantidadproductoChanged();
    #endregion
		
		public Venta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ve_idventa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ve_idventa
		{
			get
			{
				return this._ve_idventa;
			}
			set
			{
				if ((this._ve_idventa != value))
				{
					this.Onve_idventaChanging(value);
					this.SendPropertyChanging();
					this._ve_idventa = value;
					this.SendPropertyChanged("ve_idventa");
					this.Onve_idventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ve_fecha", DbType="Date NOT NULL")]
		public System.DateTime ve_fecha
		{
			get
			{
				return this._ve_fecha;
			}
			set
			{
				if ((this._ve_fecha != value))
				{
					this.Onve_fechaChanging(value);
					this.SendPropertyChanging();
					this._ve_fecha = value;
					this.SendPropertyChanged("ve_fecha");
					this.Onve_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ve_cantidadproducto", DbType="Int")]
		public System.Nullable<int> ve_cantidadproducto
		{
			get
			{
				return this._ve_cantidadproducto;
			}
			set
			{
				if ((this._ve_cantidadproducto != value))
				{
					this.Onve_cantidadproductoChanging(value);
					this.SendPropertyChanging();
					this._ve_cantidadproducto = value;
					this.SendPropertyChanged("ve_cantidadproducto");
					this.Onve_cantidadproductoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cat_idcategoria;
		
		private string _cat_nombre;
		
		private EntitySet<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncat_idcategoriaChanging(int value);
    partial void Oncat_idcategoriaChanged();
    partial void Oncat_nombreChanging(string value);
    partial void Oncat_nombreChanged();
    #endregion
		
		public Categoria()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_idcategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cat_idcategoria
		{
			get
			{
				return this._cat_idcategoria;
			}
			set
			{
				if ((this._cat_idcategoria != value))
				{
					this.Oncat_idcategoriaChanging(value);
					this.SendPropertyChanging();
					this._cat_idcategoria = value;
					this.SendPropertyChanged("cat_idcategoria");
					this.Oncat_idcategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string cat_nombre
		{
			get
			{
				return this._cat_nombre;
			}
			set
			{
				if ((this._cat_nombre != value))
				{
					this.Oncat_nombreChanging(value);
					this.SendPropertyChanging();
					this._cat_nombre = value;
					this.SendPropertyChanged("cat_nombre");
					this.Oncat_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Producto", Storage="_Producto", ThisKey="cat_idcategoria", OtherKey="pd_idcategoria")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanoDevolucion")]
	public partial class DanoDevolucion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _da_iddañodevolucion;
		
		private string _da_movimientoinventario;
		
		private string _da_tipo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onda_iddañodevolucionChanging(int value);
    partial void Onda_iddañodevolucionChanged();
    partial void Onda_movimientoinventarioChanging(string value);
    partial void Onda_movimientoinventarioChanged();
    partial void Onda_tipoChanging(string value);
    partial void Onda_tipoChanged();
    #endregion
		
		public DanoDevolucion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_da_iddañodevolucion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int da_iddañodevolucion
		{
			get
			{
				return this._da_iddañodevolucion;
			}
			set
			{
				if ((this._da_iddañodevolucion != value))
				{
					this.Onda_iddañodevolucionChanging(value);
					this.SendPropertyChanging();
					this._da_iddañodevolucion = value;
					this.SendPropertyChanged("da_iddañodevolucion");
					this.Onda_iddañodevolucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_da_movimientoinventario", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string da_movimientoinventario
		{
			get
			{
				return this._da_movimientoinventario;
			}
			set
			{
				if ((this._da_movimientoinventario != value))
				{
					this.Onda_movimientoinventarioChanging(value);
					this.SendPropertyChanging();
					this._da_movimientoinventario = value;
					this.SendPropertyChanged("da_movimientoinventario");
					this.Onda_movimientoinventarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_da_tipo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string da_tipo
		{
			get
			{
				return this._da_tipo;
			}
			set
			{
				if ((this._da_tipo != value))
				{
					this.Onda_tipoChanging(value);
					this.SendPropertyChanging();
					this._da_tipo = value;
					this.SendPropertyChanged("da_tipo");
					this.Onda_tipoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetalleCompra")]
	public partial class DetalleCompra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dtl_idordencompra;
		
		private int _dtl_cantidadproducto;
		
		private EntitySet<OrdenCompra> _OrdenCompra;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondtl_idordencompraChanging(int value);
    partial void Ondtl_idordencompraChanged();
    partial void Ondtl_cantidadproductoChanging(int value);
    partial void Ondtl_cantidadproductoChanged();
    #endregion
		
		public DetalleCompra()
		{
			this._OrdenCompra = new EntitySet<OrdenCompra>(new Action<OrdenCompra>(this.attach_OrdenCompra), new Action<OrdenCompra>(this.detach_OrdenCompra));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtl_idordencompra", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dtl_idordencompra
		{
			get
			{
				return this._dtl_idordencompra;
			}
			set
			{
				if ((this._dtl_idordencompra != value))
				{
					this.Ondtl_idordencompraChanging(value);
					this.SendPropertyChanging();
					this._dtl_idordencompra = value;
					this.SendPropertyChanged("dtl_idordencompra");
					this.Ondtl_idordencompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtl_cantidadproducto", DbType="Int NOT NULL")]
		public int dtl_cantidadproducto
		{
			get
			{
				return this._dtl_cantidadproducto;
			}
			set
			{
				if ((this._dtl_cantidadproducto != value))
				{
					this.Ondtl_cantidadproductoChanging(value);
					this.SendPropertyChanging();
					this._dtl_cantidadproducto = value;
					this.SendPropertyChanged("dtl_cantidadproducto");
					this.Ondtl_cantidadproductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DetalleCompra_OrdenCompra", Storage="_OrdenCompra", ThisKey="dtl_idordencompra", OtherKey="or_detalle")]
		public EntitySet<OrdenCompra> OrdenCompra
		{
			get
			{
				return this._OrdenCompra;
			}
			set
			{
				this._OrdenCompra.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OrdenCompra(OrdenCompra entity)
		{
			this.SendPropertyChanging();
			entity.DetalleCompra = this;
		}
		
		private void detach_OrdenCompra(OrdenCompra entity)
		{
			this.SendPropertyChanging();
			entity.DetalleCompra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _em_identificacion;
		
		private System.DateTime _em_fechanacimiento;
		
		private string _em_nombre;
		
		private string _em_tipoid;
		
		private string _em_direccion;
		
		private string _em_cargo;
		
		private string _em_contacto;
		
		private System.DateTime _em_fechaentrada;
		
		private string _em_estado;
		
		private EntitySet<MovimientoInventario> _MovimientoInventario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onem_identificacionChanging(string value);
    partial void Onem_identificacionChanged();
    partial void Onem_fechanacimientoChanging(System.DateTime value);
    partial void Onem_fechanacimientoChanged();
    partial void Onem_nombreChanging(string value);
    partial void Onem_nombreChanged();
    partial void Onem_tipoidChanging(string value);
    partial void Onem_tipoidChanged();
    partial void Onem_direccionChanging(string value);
    partial void Onem_direccionChanged();
    partial void Onem_cargoChanging(string value);
    partial void Onem_cargoChanged();
    partial void Onem_contactoChanging(string value);
    partial void Onem_contactoChanged();
    partial void Onem_fechaentradaChanging(System.DateTime value);
    partial void Onem_fechaentradaChanged();
    partial void Onem_estadoChanging(string value);
    partial void Onem_estadoChanged();
    #endregion
		
		public Empleado()
		{
			this._MovimientoInventario = new EntitySet<MovimientoInventario>(new Action<MovimientoInventario>(this.attach_MovimientoInventario), new Action<MovimientoInventario>(this.detach_MovimientoInventario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_identificacion", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string em_identificacion
		{
			get
			{
				return this._em_identificacion;
			}
			set
			{
				if ((this._em_identificacion != value))
				{
					this.Onem_identificacionChanging(value);
					this.SendPropertyChanging();
					this._em_identificacion = value;
					this.SendPropertyChanged("em_identificacion");
					this.Onem_identificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_fechanacimiento", DbType="Date NOT NULL")]
		public System.DateTime em_fechanacimiento
		{
			get
			{
				return this._em_fechanacimiento;
			}
			set
			{
				if ((this._em_fechanacimiento != value))
				{
					this.Onem_fechanacimientoChanging(value);
					this.SendPropertyChanging();
					this._em_fechanacimiento = value;
					this.SendPropertyChanged("em_fechanacimiento");
					this.Onem_fechanacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string em_nombre
		{
			get
			{
				return this._em_nombre;
			}
			set
			{
				if ((this._em_nombre != value))
				{
					this.Onem_nombreChanging(value);
					this.SendPropertyChanging();
					this._em_nombre = value;
					this.SendPropertyChanged("em_nombre");
					this.Onem_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_tipoid", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string em_tipoid
		{
			get
			{
				return this._em_tipoid;
			}
			set
			{
				if ((this._em_tipoid != value))
				{
					this.Onem_tipoidChanging(value);
					this.SendPropertyChanging();
					this._em_tipoid = value;
					this.SendPropertyChanged("em_tipoid");
					this.Onem_tipoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_direccion
		{
			get
			{
				return this._em_direccion;
			}
			set
			{
				if ((this._em_direccion != value))
				{
					this.Onem_direccionChanging(value);
					this.SendPropertyChanging();
					this._em_direccion = value;
					this.SendPropertyChanged("em_direccion");
					this.Onem_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_cargo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_cargo
		{
			get
			{
				return this._em_cargo;
			}
			set
			{
				if ((this._em_cargo != value))
				{
					this.Onem_cargoChanging(value);
					this.SendPropertyChanging();
					this._em_cargo = value;
					this.SendPropertyChanged("em_cargo");
					this.Onem_cargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_contacto", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string em_contacto
		{
			get
			{
				return this._em_contacto;
			}
			set
			{
				if ((this._em_contacto != value))
				{
					this.Onem_contactoChanging(value);
					this.SendPropertyChanging();
					this._em_contacto = value;
					this.SendPropertyChanged("em_contacto");
					this.Onem_contactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_fechaentrada", DbType="Date NOT NULL")]
		public System.DateTime em_fechaentrada
		{
			get
			{
				return this._em_fechaentrada;
			}
			set
			{
				if ((this._em_fechaentrada != value))
				{
					this.Onem_fechaentradaChanging(value);
					this.SendPropertyChanging();
					this._em_fechaentrada = value;
					this.SendPropertyChanged("em_fechaentrada");
					this.Onem_fechaentradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_estado
		{
			get
			{
				return this._em_estado;
			}
			set
			{
				if ((this._em_estado != value))
				{
					this.Onem_estadoChanging(value);
					this.SendPropertyChanging();
					this._em_estado = value;
					this.SendPropertyChanged("em_estado");
					this.Onem_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_MovimientoInventario", Storage="_MovimientoInventario", ThisKey="em_identificacion", OtherKey="mov_identificacionEmp")]
		public EntitySet<MovimientoInventario> MovimientoInventario
		{
			get
			{
				return this._MovimientoInventario;
			}
			set
			{
				this._MovimientoInventario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MovimientoInventario(MovimientoInventario entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_MovimientoInventario(MovimientoInventario entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Items")]
	public partial class Items : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _it_iditems;
		
		private string _it_observacion;
		
		private string _it_texto;
		
		private bool _it_calificacion;
		
		private EntitySet<ListaChequeo> _ListaChequeo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onit_iditemsChanging(int value);
    partial void Onit_iditemsChanged();
    partial void Onit_observacionChanging(string value);
    partial void Onit_observacionChanged();
    partial void Onit_textoChanging(string value);
    partial void Onit_textoChanged();
    partial void Onit_calificacionChanging(bool value);
    partial void Onit_calificacionChanged();
    #endregion
		
		public Items()
		{
			this._ListaChequeo = new EntitySet<ListaChequeo>(new Action<ListaChequeo>(this.attach_ListaChequeo), new Action<ListaChequeo>(this.detach_ListaChequeo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_it_iditems", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int it_iditems
		{
			get
			{
				return this._it_iditems;
			}
			set
			{
				if ((this._it_iditems != value))
				{
					this.Onit_iditemsChanging(value);
					this.SendPropertyChanging();
					this._it_iditems = value;
					this.SendPropertyChanged("it_iditems");
					this.Onit_iditemsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_it_observacion", DbType="VarChar(150)")]
		public string it_observacion
		{
			get
			{
				return this._it_observacion;
			}
			set
			{
				if ((this._it_observacion != value))
				{
					this.Onit_observacionChanging(value);
					this.SendPropertyChanging();
					this._it_observacion = value;
					this.SendPropertyChanged("it_observacion");
					this.Onit_observacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_it_texto", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string it_texto
		{
			get
			{
				return this._it_texto;
			}
			set
			{
				if ((this._it_texto != value))
				{
					this.Onit_textoChanging(value);
					this.SendPropertyChanging();
					this._it_texto = value;
					this.SendPropertyChanged("it_texto");
					this.Onit_textoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_it_calificacion", DbType="Bit NOT NULL")]
		public bool it_calificacion
		{
			get
			{
				return this._it_calificacion;
			}
			set
			{
				if ((this._it_calificacion != value))
				{
					this.Onit_calificacionChanging(value);
					this.SendPropertyChanging();
					this._it_calificacion = value;
					this.SendPropertyChanged("it_calificacion");
					this.Onit_calificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Items_ListaChequeo", Storage="_ListaChequeo", ThisKey="it_iditems", OtherKey="li_iditems")]
		public EntitySet<ListaChequeo> ListaChequeo
		{
			get
			{
				return this._ListaChequeo;
			}
			set
			{
				this._ListaChequeo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ListaChequeo(ListaChequeo entity)
		{
			this.SendPropertyChanging();
			entity.Items = this;
		}
		
		private void detach_ListaChequeo(ListaChequeo entity)
		{
			this.SendPropertyChanging();
			entity.Items = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ListaChequeo")]
	public partial class ListaChequeo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _li_idlista;
		
		private System.DateTime _li_fecha;
		
		private System.Nullable<int> _li_iditems;
		
		private int _li_serie;
		
		private string _li_pregunta;
		
		private bool _li_calificacion;
		
		private EntitySet<CambioCliente> _CambioCliente;
		
		private EntitySet<OrdenCompra> _OrdenCompra;
		
		private EntityRef<Items> _Items;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onli_idlistaChanging(int value);
    partial void Onli_idlistaChanged();
    partial void Onli_fechaChanging(System.DateTime value);
    partial void Onli_fechaChanged();
    partial void Onli_iditemsChanging(System.Nullable<int> value);
    partial void Onli_iditemsChanged();
    partial void Onli_serieChanging(int value);
    partial void Onli_serieChanged();
    partial void Onli_preguntaChanging(string value);
    partial void Onli_preguntaChanged();
    partial void Onli_calificacionChanging(bool value);
    partial void Onli_calificacionChanged();
    #endregion
		
		public ListaChequeo()
		{
			this._CambioCliente = new EntitySet<CambioCliente>(new Action<CambioCliente>(this.attach_CambioCliente), new Action<CambioCliente>(this.detach_CambioCliente));
			this._OrdenCompra = new EntitySet<OrdenCompra>(new Action<OrdenCompra>(this.attach_OrdenCompra), new Action<OrdenCompra>(this.detach_OrdenCompra));
			this._Items = default(EntityRef<Items>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_li_idlista", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int li_idlista
		{
			get
			{
				return this._li_idlista;
			}
			set
			{
				if ((this._li_idlista != value))
				{
					this.Onli_idlistaChanging(value);
					this.SendPropertyChanging();
					this._li_idlista = value;
					this.SendPropertyChanged("li_idlista");
					this.Onli_idlistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_li_fecha", DbType="Date NOT NULL")]
		public System.DateTime li_fecha
		{
			get
			{
				return this._li_fecha;
			}
			set
			{
				if ((this._li_fecha != value))
				{
					this.Onli_fechaChanging(value);
					this.SendPropertyChanging();
					this._li_fecha = value;
					this.SendPropertyChanged("li_fecha");
					this.Onli_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_li_iditems", DbType="Int")]
		public System.Nullable<int> li_iditems
		{
			get
			{
				return this._li_iditems;
			}
			set
			{
				if ((this._li_iditems != value))
				{
					if (this._Items.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onli_iditemsChanging(value);
					this.SendPropertyChanging();
					this._li_iditems = value;
					this.SendPropertyChanged("li_iditems");
					this.Onli_iditemsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_li_serie", DbType="Int NOT NULL")]
		public int li_serie
		{
			get
			{
				return this._li_serie;
			}
			set
			{
				if ((this._li_serie != value))
				{
					this.Onli_serieChanging(value);
					this.SendPropertyChanging();
					this._li_serie = value;
					this.SendPropertyChanged("li_serie");
					this.Onli_serieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_li_pregunta", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string li_pregunta
		{
			get
			{
				return this._li_pregunta;
			}
			set
			{
				if ((this._li_pregunta != value))
				{
					this.Onli_preguntaChanging(value);
					this.SendPropertyChanging();
					this._li_pregunta = value;
					this.SendPropertyChanged("li_pregunta");
					this.Onli_preguntaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_li_calificacion", DbType="Bit NOT NULL")]
		public bool li_calificacion
		{
			get
			{
				return this._li_calificacion;
			}
			set
			{
				if ((this._li_calificacion != value))
				{
					this.Onli_calificacionChanging(value);
					this.SendPropertyChanging();
					this._li_calificacion = value;
					this.SendPropertyChanged("li_calificacion");
					this.Onli_calificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ListaChequeo_CambioCliente", Storage="_CambioCliente", ThisKey="li_idlista", OtherKey="ca_idlista")]
		public EntitySet<CambioCliente> CambioCliente
		{
			get
			{
				return this._CambioCliente;
			}
			set
			{
				this._CambioCliente.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ListaChequeo_OrdenCompra", Storage="_OrdenCompra", ThisKey="li_idlista", OtherKey="or_lista")]
		public EntitySet<OrdenCompra> OrdenCompra
		{
			get
			{
				return this._OrdenCompra;
			}
			set
			{
				this._OrdenCompra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Items_ListaChequeo", Storage="_Items", ThisKey="li_iditems", OtherKey="it_iditems", IsForeignKey=true)]
		public Items Items
		{
			get
			{
				return this._Items.Entity;
			}
			set
			{
				Items previousValue = this._Items.Entity;
				if (((previousValue != value) 
							|| (this._Items.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Items.Entity = null;
						previousValue.ListaChequeo.Remove(this);
					}
					this._Items.Entity = value;
					if ((value != null))
					{
						value.ListaChequeo.Add(this);
						this._li_iditems = value.it_iditems;
					}
					else
					{
						this._li_iditems = default(Nullable<int>);
					}
					this.SendPropertyChanged("Items");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CambioCliente(CambioCliente entity)
		{
			this.SendPropertyChanging();
			entity.ListaChequeo = this;
		}
		
		private void detach_CambioCliente(CambioCliente entity)
		{
			this.SendPropertyChanging();
			entity.ListaChequeo = null;
		}
		
		private void attach_OrdenCompra(OrdenCompra entity)
		{
			this.SendPropertyChanging();
			entity.ListaChequeo = this;
		}
		
		private void detach_OrdenCompra(OrdenCompra entity)
		{
			this.SendPropertyChanging();
			entity.ListaChequeo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MovimientoInventario")]
	public partial class MovimientoInventario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mov_idmovimiento;
		
		private string _mov_identificacionEmp;
		
		private System.Nullable<int> _mov_idproducto;
		
		private System.Nullable<int> _mov_idtipo;
		
		private System.DateTime _mov_fecha;
		
		private System.DateTime _mov_fechavencimiento;
		
		private string _mov_ubicacion;
		
		private int _mov_cantidadproductos;
		
		private EntityRef<Empleado> _Empleado;
		
		private EntityRef<Tipo> _Tipo;
		
		private EntityRef<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmov_idmovimientoChanging(int value);
    partial void Onmov_idmovimientoChanged();
    partial void Onmov_identificacionEmpChanging(string value);
    partial void Onmov_identificacionEmpChanged();
    partial void Onmov_idproductoChanging(System.Nullable<int> value);
    partial void Onmov_idproductoChanged();
    partial void Onmov_idtipoChanging(System.Nullable<int> value);
    partial void Onmov_idtipoChanged();
    partial void Onmov_fechaChanging(System.DateTime value);
    partial void Onmov_fechaChanged();
    partial void Onmov_fechavencimientoChanging(System.DateTime value);
    partial void Onmov_fechavencimientoChanged();
    partial void Onmov_ubicacionChanging(string value);
    partial void Onmov_ubicacionChanged();
    partial void Onmov_cantidadproductosChanging(int value);
    partial void Onmov_cantidadproductosChanged();
    #endregion
		
		public MovimientoInventario()
		{
			this._Empleado = default(EntityRef<Empleado>);
			this._Tipo = default(EntityRef<Tipo>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_idmovimiento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mov_idmovimiento
		{
			get
			{
				return this._mov_idmovimiento;
			}
			set
			{
				if ((this._mov_idmovimiento != value))
				{
					this.Onmov_idmovimientoChanging(value);
					this.SendPropertyChanging();
					this._mov_idmovimiento = value;
					this.SendPropertyChanged("mov_idmovimiento");
					this.Onmov_idmovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_identificacionEmp", DbType="VarChar(30)")]
		public string mov_identificacionEmp
		{
			get
			{
				return this._mov_identificacionEmp;
			}
			set
			{
				if ((this._mov_identificacionEmp != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmov_identificacionEmpChanging(value);
					this.SendPropertyChanging();
					this._mov_identificacionEmp = value;
					this.SendPropertyChanged("mov_identificacionEmp");
					this.Onmov_identificacionEmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_idproducto", DbType="Int")]
		public System.Nullable<int> mov_idproducto
		{
			get
			{
				return this._mov_idproducto;
			}
			set
			{
				if ((this._mov_idproducto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmov_idproductoChanging(value);
					this.SendPropertyChanging();
					this._mov_idproducto = value;
					this.SendPropertyChanged("mov_idproducto");
					this.Onmov_idproductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_idtipo", DbType="Int")]
		public System.Nullable<int> mov_idtipo
		{
			get
			{
				return this._mov_idtipo;
			}
			set
			{
				if ((this._mov_idtipo != value))
				{
					if (this._Tipo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmov_idtipoChanging(value);
					this.SendPropertyChanging();
					this._mov_idtipo = value;
					this.SendPropertyChanged("mov_idtipo");
					this.Onmov_idtipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_fecha", DbType="Date NOT NULL")]
		public System.DateTime mov_fecha
		{
			get
			{
				return this._mov_fecha;
			}
			set
			{
				if ((this._mov_fecha != value))
				{
					this.Onmov_fechaChanging(value);
					this.SendPropertyChanging();
					this._mov_fecha = value;
					this.SendPropertyChanged("mov_fecha");
					this.Onmov_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_fechavencimiento", DbType="Date NOT NULL")]
		public System.DateTime mov_fechavencimiento
		{
			get
			{
				return this._mov_fechavencimiento;
			}
			set
			{
				if ((this._mov_fechavencimiento != value))
				{
					this.Onmov_fechavencimientoChanging(value);
					this.SendPropertyChanging();
					this._mov_fechavencimiento = value;
					this.SendPropertyChanged("mov_fechavencimiento");
					this.Onmov_fechavencimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_ubicacion", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string mov_ubicacion
		{
			get
			{
				return this._mov_ubicacion;
			}
			set
			{
				if ((this._mov_ubicacion != value))
				{
					this.Onmov_ubicacionChanging(value);
					this.SendPropertyChanging();
					this._mov_ubicacion = value;
					this.SendPropertyChanged("mov_ubicacion");
					this.Onmov_ubicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_cantidadproductos", DbType="Int NOT NULL")]
		public int mov_cantidadproductos
		{
			get
			{
				return this._mov_cantidadproductos;
			}
			set
			{
				if ((this._mov_cantidadproductos != value))
				{
					this.Onmov_cantidadproductosChanging(value);
					this.SendPropertyChanging();
					this._mov_cantidadproductos = value;
					this.SendPropertyChanged("mov_cantidadproductos");
					this.Onmov_cantidadproductosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_MovimientoInventario", Storage="_Empleado", ThisKey="mov_identificacionEmp", OtherKey="em_identificacion", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.MovimientoInventario.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.MovimientoInventario.Add(this);
						this._mov_identificacionEmp = value.em_identificacion;
					}
					else
					{
						this._mov_identificacionEmp = default(string);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_MovimientoInventario", Storage="_Tipo", ThisKey="mov_idtipo", OtherKey="ti_idtipo", IsForeignKey=true)]
		public Tipo Tipo
		{
			get
			{
				return this._Tipo.Entity;
			}
			set
			{
				Tipo previousValue = this._Tipo.Entity;
				if (((previousValue != value) 
							|| (this._Tipo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo.Entity = null;
						previousValue.MovimientoInventario.Remove(this);
					}
					this._Tipo.Entity = value;
					if ((value != null))
					{
						value.MovimientoInventario.Add(this);
						this._mov_idtipo = value.ti_idtipo;
					}
					else
					{
						this._mov_idtipo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tipo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_MovimientoInventario", Storage="_Producto", ThisKey="mov_idproducto", OtherKey="pd_idproducto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.MovimientoInventario.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.MovimientoInventario.Add(this);
						this._mov_idproducto = value.pd_idproducto;
					}
					else
					{
						this._mov_idproducto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrdenCompra")]
	public partial class OrdenCompra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _or_idordencompra;
		
		private System.Nullable<int> _or_detalle;
		
		private System.Nullable<int> _or_lista;
		
		private System.Nullable<int> _or_idproveedor;
		
		private System.DateTime _or_fecha;
		
		private decimal _or_total;
		
		private EntityRef<DetalleCompra> _DetalleCompra;
		
		private EntityRef<ListaChequeo> _ListaChequeo;
		
		private EntityRef<Proveedor> _Proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onor_idordencompraChanging(int value);
    partial void Onor_idordencompraChanged();
    partial void Onor_detalleChanging(System.Nullable<int> value);
    partial void Onor_detalleChanged();
    partial void Onor_listaChanging(System.Nullable<int> value);
    partial void Onor_listaChanged();
    partial void Onor_idproveedorChanging(System.Nullable<int> value);
    partial void Onor_idproveedorChanged();
    partial void Onor_fechaChanging(System.DateTime value);
    partial void Onor_fechaChanged();
    partial void Onor_totalChanging(decimal value);
    partial void Onor_totalChanged();
    #endregion
		
		public OrdenCompra()
		{
			this._DetalleCompra = default(EntityRef<DetalleCompra>);
			this._ListaChequeo = default(EntityRef<ListaChequeo>);
			this._Proveedor = default(EntityRef<Proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_or_idordencompra", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int or_idordencompra
		{
			get
			{
				return this._or_idordencompra;
			}
			set
			{
				if ((this._or_idordencompra != value))
				{
					this.Onor_idordencompraChanging(value);
					this.SendPropertyChanging();
					this._or_idordencompra = value;
					this.SendPropertyChanged("or_idordencompra");
					this.Onor_idordencompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_or_detalle", DbType="Int")]
		public System.Nullable<int> or_detalle
		{
			get
			{
				return this._or_detalle;
			}
			set
			{
				if ((this._or_detalle != value))
				{
					if (this._DetalleCompra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onor_detalleChanging(value);
					this.SendPropertyChanging();
					this._or_detalle = value;
					this.SendPropertyChanged("or_detalle");
					this.Onor_detalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_or_lista", DbType="Int")]
		public System.Nullable<int> or_lista
		{
			get
			{
				return this._or_lista;
			}
			set
			{
				if ((this._or_lista != value))
				{
					if (this._ListaChequeo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onor_listaChanging(value);
					this.SendPropertyChanging();
					this._or_lista = value;
					this.SendPropertyChanged("or_lista");
					this.Onor_listaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_or_idproveedor", DbType="Int")]
		public System.Nullable<int> or_idproveedor
		{
			get
			{
				return this._or_idproveedor;
			}
			set
			{
				if ((this._or_idproveedor != value))
				{
					if (this._Proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onor_idproveedorChanging(value);
					this.SendPropertyChanging();
					this._or_idproveedor = value;
					this.SendPropertyChanged("or_idproveedor");
					this.Onor_idproveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_or_fecha", DbType="Date NOT NULL")]
		public System.DateTime or_fecha
		{
			get
			{
				return this._or_fecha;
			}
			set
			{
				if ((this._or_fecha != value))
				{
					this.Onor_fechaChanging(value);
					this.SendPropertyChanging();
					this._or_fecha = value;
					this.SendPropertyChanged("or_fecha");
					this.Onor_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_or_total", DbType="Money NOT NULL")]
		public decimal or_total
		{
			get
			{
				return this._or_total;
			}
			set
			{
				if ((this._or_total != value))
				{
					this.Onor_totalChanging(value);
					this.SendPropertyChanging();
					this._or_total = value;
					this.SendPropertyChanged("or_total");
					this.Onor_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DetalleCompra_OrdenCompra", Storage="_DetalleCompra", ThisKey="or_detalle", OtherKey="dtl_idordencompra", IsForeignKey=true)]
		public DetalleCompra DetalleCompra
		{
			get
			{
				return this._DetalleCompra.Entity;
			}
			set
			{
				DetalleCompra previousValue = this._DetalleCompra.Entity;
				if (((previousValue != value) 
							|| (this._DetalleCompra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DetalleCompra.Entity = null;
						previousValue.OrdenCompra.Remove(this);
					}
					this._DetalleCompra.Entity = value;
					if ((value != null))
					{
						value.OrdenCompra.Add(this);
						this._or_detalle = value.dtl_idordencompra;
					}
					else
					{
						this._or_detalle = default(Nullable<int>);
					}
					this.SendPropertyChanged("DetalleCompra");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ListaChequeo_OrdenCompra", Storage="_ListaChequeo", ThisKey="or_lista", OtherKey="li_idlista", IsForeignKey=true)]
		public ListaChequeo ListaChequeo
		{
			get
			{
				return this._ListaChequeo.Entity;
			}
			set
			{
				ListaChequeo previousValue = this._ListaChequeo.Entity;
				if (((previousValue != value) 
							|| (this._ListaChequeo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ListaChequeo.Entity = null;
						previousValue.OrdenCompra.Remove(this);
					}
					this._ListaChequeo.Entity = value;
					if ((value != null))
					{
						value.OrdenCompra.Add(this);
						this._or_lista = value.li_idlista;
					}
					else
					{
						this._or_lista = default(Nullable<int>);
					}
					this.SendPropertyChanged("ListaChequeo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedor_OrdenCompra", Storage="_Proveedor", ThisKey="or_idproveedor", OtherKey="pro_idproveedor", IsForeignKey=true)]
		public Proveedor Proveedor
		{
			get
			{
				return this._Proveedor.Entity;
			}
			set
			{
				Proveedor previousValue = this._Proveedor.Entity;
				if (((previousValue != value) 
							|| (this._Proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proveedor.Entity = null;
						previousValue.OrdenCompra.Remove(this);
					}
					this._Proveedor.Entity = value;
					if ((value != null))
					{
						value.OrdenCompra.Add(this);
						this._or_idproveedor = value.pro_idproveedor;
					}
					else
					{
						this._or_idproveedor = default(Nullable<int>);
					}
					this.SendPropertyChanged("Proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proveedor")]
	public partial class Proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_idproveedor;
		
		private System.Nullable<bool> _pro_estado;
		
		private long _pro_contacto;
		
		private string _pro_direccion;
		
		private string _pro_nombreempresa;
		
		private EntitySet<OrdenCompra> _OrdenCompra;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idproveedorChanging(int value);
    partial void Onpro_idproveedorChanged();
    partial void Onpro_estadoChanging(System.Nullable<bool> value);
    partial void Onpro_estadoChanged();
    partial void Onpro_contactoChanging(long value);
    partial void Onpro_contactoChanged();
    partial void Onpro_direccionChanging(string value);
    partial void Onpro_direccionChanged();
    partial void Onpro_nombreempresaChanging(string value);
    partial void Onpro_nombreempresaChanged();
    #endregion
		
		public Proveedor()
		{
			this._OrdenCompra = new EntitySet<OrdenCompra>(new Action<OrdenCompra>(this.attach_OrdenCompra), new Action<OrdenCompra>(this.detach_OrdenCompra));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_idproveedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pro_idproveedor
		{
			get
			{
				return this._pro_idproveedor;
			}
			set
			{
				if ((this._pro_idproveedor != value))
				{
					this.Onpro_idproveedorChanging(value);
					this.SendPropertyChanging();
					this._pro_idproveedor = value;
					this.SendPropertyChanged("pro_idproveedor");
					this.Onpro_idproveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Bit")]
		public System.Nullable<bool> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_contacto", DbType="BigInt NOT NULL")]
		public long pro_contacto
		{
			get
			{
				return this._pro_contacto;
			}
			set
			{
				if ((this._pro_contacto != value))
				{
					this.Onpro_contactoChanging(value);
					this.SendPropertyChanging();
					this._pro_contacto = value;
					this.SendPropertyChanged("pro_contacto");
					this.Onpro_contactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pro_direccion
		{
			get
			{
				return this._pro_direccion;
			}
			set
			{
				if ((this._pro_direccion != value))
				{
					this.Onpro_direccionChanging(value);
					this.SendPropertyChanging();
					this._pro_direccion = value;
					this.SendPropertyChanged("pro_direccion");
					this.Onpro_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombreempresa", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string pro_nombreempresa
		{
			get
			{
				return this._pro_nombreempresa;
			}
			set
			{
				if ((this._pro_nombreempresa != value))
				{
					this.Onpro_nombreempresaChanging(value);
					this.SendPropertyChanging();
					this._pro_nombreempresa = value;
					this.SendPropertyChanged("pro_nombreempresa");
					this.Onpro_nombreempresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedor_OrdenCompra", Storage="_OrdenCompra", ThisKey="pro_idproveedor", OtherKey="or_idproveedor")]
		public EntitySet<OrdenCompra> OrdenCompra
		{
			get
			{
				return this._OrdenCompra;
			}
			set
			{
				this._OrdenCompra.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OrdenCompra(OrdenCompra entity)
		{
			this.SendPropertyChanging();
			entity.Proveedor = this;
		}
		
		private void detach_OrdenCompra(OrdenCompra entity)
		{
			this.SendPropertyChanging();
			entity.Proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo")]
	public partial class Tipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ti_idtipo;
		
		private string _ti_nombre;
		
		private string _ti_descripcion;
		
		private EntitySet<MovimientoInventario> _MovimientoInventario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onti_idtipoChanging(int value);
    partial void Onti_idtipoChanged();
    partial void Onti_nombreChanging(string value);
    partial void Onti_nombreChanged();
    partial void Onti_descripcionChanging(string value);
    partial void Onti_descripcionChanged();
    #endregion
		
		public Tipo()
		{
			this._MovimientoInventario = new EntitySet<MovimientoInventario>(new Action<MovimientoInventario>(this.attach_MovimientoInventario), new Action<MovimientoInventario>(this.detach_MovimientoInventario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ti_idtipo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ti_idtipo
		{
			get
			{
				return this._ti_idtipo;
			}
			set
			{
				if ((this._ti_idtipo != value))
				{
					this.Onti_idtipoChanging(value);
					this.SendPropertyChanging();
					this._ti_idtipo = value;
					this.SendPropertyChanged("ti_idtipo");
					this.Onti_idtipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ti_nombre", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string ti_nombre
		{
			get
			{
				return this._ti_nombre;
			}
			set
			{
				if ((this._ti_nombre != value))
				{
					this.Onti_nombreChanging(value);
					this.SendPropertyChanging();
					this._ti_nombre = value;
					this.SendPropertyChanged("ti_nombre");
					this.Onti_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ti_descripcion", DbType="VarChar(60)")]
		public string ti_descripcion
		{
			get
			{
				return this._ti_descripcion;
			}
			set
			{
				if ((this._ti_descripcion != value))
				{
					this.Onti_descripcionChanging(value);
					this.SendPropertyChanging();
					this._ti_descripcion = value;
					this.SendPropertyChanged("ti_descripcion");
					this.Onti_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_MovimientoInventario", Storage="_MovimientoInventario", ThisKey="ti_idtipo", OtherKey="mov_idtipo")]
		public EntitySet<MovimientoInventario> MovimientoInventario
		{
			get
			{
				return this._MovimientoInventario;
			}
			set
			{
				this._MovimientoInventario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MovimientoInventario(MovimientoInventario entity)
		{
			this.SendPropertyChanging();
			entity.Tipo = this;
		}
		
		private void detach_MovimientoInventario(MovimientoInventario entity)
		{
			this.SendPropertyChanging();
			entity.Tipo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pd_idproducto;
		
		private string _pd_nombre;
		
		private string _pd_marca;
		
		private int _pd_stockmin;
		
		private int _pd_stockmax;
		
		private double _pd_peso;
		
		private decimal _pd_precioventa;
		
		private decimal _pd_preciocompra;
		
		private string _pd_estado;
		
		private int _pd_cantidadproductos;
		
		private System.Nullable<int> _pd_idcategoria;
		
		private EntitySet<MovimientoInventario> _MovimientoInventario;
		
		private EntityRef<Categoria> _Categoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpd_idproductoChanging(int value);
    partial void Onpd_idproductoChanged();
    partial void Onpd_nombreChanging(string value);
    partial void Onpd_nombreChanged();
    partial void Onpd_marcaChanging(string value);
    partial void Onpd_marcaChanged();
    partial void Onpd_stockminChanging(int value);
    partial void Onpd_stockminChanged();
    partial void Onpd_stockmaxChanging(int value);
    partial void Onpd_stockmaxChanged();
    partial void Onpd_pesoChanging(double value);
    partial void Onpd_pesoChanged();
    partial void Onpd_precioventaChanging(decimal value);
    partial void Onpd_precioventaChanged();
    partial void Onpd_preciocompraChanging(decimal value);
    partial void Onpd_preciocompraChanged();
    partial void Onpd_estadoChanging(string value);
    partial void Onpd_estadoChanged();
    partial void Onpd_cantidadproductosChanging(int value);
    partial void Onpd_cantidadproductosChanged();
    partial void Onpd_idcategoriaChanging(System.Nullable<int> value);
    partial void Onpd_idcategoriaChanged();
    #endregion
		
		public Producto()
		{
			this._MovimientoInventario = new EntitySet<MovimientoInventario>(new Action<MovimientoInventario>(this.attach_MovimientoInventario), new Action<MovimientoInventario>(this.detach_MovimientoInventario));
			this._Categoria = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_idproducto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pd_idproducto
		{
			get
			{
				return this._pd_idproducto;
			}
			set
			{
				if ((this._pd_idproducto != value))
				{
					this.Onpd_idproductoChanging(value);
					this.SendPropertyChanging();
					this._pd_idproducto = value;
					this.SendPropertyChanged("pd_idproducto");
					this.Onpd_idproductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string pd_nombre
		{
			get
			{
				return this._pd_nombre;
			}
			set
			{
				if ((this._pd_nombre != value))
				{
					this.Onpd_nombreChanging(value);
					this.SendPropertyChanging();
					this._pd_nombre = value;
					this.SendPropertyChanged("pd_nombre");
					this.Onpd_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_marca", DbType="VarChar(50)")]
		public string pd_marca
		{
			get
			{
				return this._pd_marca;
			}
			set
			{
				if ((this._pd_marca != value))
				{
					this.Onpd_marcaChanging(value);
					this.SendPropertyChanging();
					this._pd_marca = value;
					this.SendPropertyChanged("pd_marca");
					this.Onpd_marcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_stockmin", DbType="Int NOT NULL")]
		public int pd_stockmin
		{
			get
			{
				return this._pd_stockmin;
			}
			set
			{
				if ((this._pd_stockmin != value))
				{
					this.Onpd_stockminChanging(value);
					this.SendPropertyChanging();
					this._pd_stockmin = value;
					this.SendPropertyChanged("pd_stockmin");
					this.Onpd_stockminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_stockmax", DbType="Int NOT NULL")]
		public int pd_stockmax
		{
			get
			{
				return this._pd_stockmax;
			}
			set
			{
				if ((this._pd_stockmax != value))
				{
					this.Onpd_stockmaxChanging(value);
					this.SendPropertyChanging();
					this._pd_stockmax = value;
					this.SendPropertyChanged("pd_stockmax");
					this.Onpd_stockmaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_peso", DbType="Float NOT NULL")]
		public double pd_peso
		{
			get
			{
				return this._pd_peso;
			}
			set
			{
				if ((this._pd_peso != value))
				{
					this.Onpd_pesoChanging(value);
					this.SendPropertyChanging();
					this._pd_peso = value;
					this.SendPropertyChanged("pd_peso");
					this.Onpd_pesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_precioventa", DbType="Money NOT NULL")]
		public decimal pd_precioventa
		{
			get
			{
				return this._pd_precioventa;
			}
			set
			{
				if ((this._pd_precioventa != value))
				{
					this.Onpd_precioventaChanging(value);
					this.SendPropertyChanging();
					this._pd_precioventa = value;
					this.SendPropertyChanged("pd_precioventa");
					this.Onpd_precioventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_preciocompra", DbType="Money NOT NULL")]
		public decimal pd_preciocompra
		{
			get
			{
				return this._pd_preciocompra;
			}
			set
			{
				if ((this._pd_preciocompra != value))
				{
					this.Onpd_preciocompraChanging(value);
					this.SendPropertyChanging();
					this._pd_preciocompra = value;
					this.SendPropertyChanged("pd_preciocompra");
					this.Onpd_preciocompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pd_estado
		{
			get
			{
				return this._pd_estado;
			}
			set
			{
				if ((this._pd_estado != value))
				{
					this.Onpd_estadoChanging(value);
					this.SendPropertyChanging();
					this._pd_estado = value;
					this.SendPropertyChanged("pd_estado");
					this.Onpd_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_cantidadproductos", DbType="Int NOT NULL")]
		public int pd_cantidadproductos
		{
			get
			{
				return this._pd_cantidadproductos;
			}
			set
			{
				if ((this._pd_cantidadproductos != value))
				{
					this.Onpd_cantidadproductosChanging(value);
					this.SendPropertyChanging();
					this._pd_cantidadproductos = value;
					this.SendPropertyChanged("pd_cantidadproductos");
					this.Onpd_cantidadproductosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_idcategoria", DbType="Int")]
		public System.Nullable<int> pd_idcategoria
		{
			get
			{
				return this._pd_idcategoria;
			}
			set
			{
				if ((this._pd_idcategoria != value))
				{
					if (this._Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpd_idcategoriaChanging(value);
					this.SendPropertyChanging();
					this._pd_idcategoria = value;
					this.SendPropertyChanged("pd_idcategoria");
					this.Onpd_idcategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_MovimientoInventario", Storage="_MovimientoInventario", ThisKey="pd_idproducto", OtherKey="mov_idproducto")]
		public EntitySet<MovimientoInventario> MovimientoInventario
		{
			get
			{
				return this._MovimientoInventario;
			}
			set
			{
				this._MovimientoInventario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Producto", Storage="_Categoria", ThisKey="pd_idcategoria", OtherKey="cat_idcategoria", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._pd_idcategoria = value.cat_idcategoria;
					}
					else
					{
						this._pd_idcategoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MovimientoInventario(MovimientoInventario entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_MovimientoInventario(MovimientoInventario entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	public partial class validarUsuarioResult
	{
		
		private string _em_identificacion;
		
		private System.DateTime _em_fechanacimiento;
		
		private string _em_nombre;
		
		private string _em_contrasena;
		
		private string _em_tipoid;
		
		private string _em_direccion;
		
		private string _em_cargo;
		
		private string _em_contacto;
		
		private System.DateTime _em_fechaentrada;
		
		private string _em_estado;
		
		public validarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_identificacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string em_identificacion
		{
			get
			{
				return this._em_identificacion;
			}
			set
			{
				if ((this._em_identificacion != value))
				{
					this._em_identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_fechanacimiento", DbType="Date NOT NULL")]
		public System.DateTime em_fechanacimiento
		{
			get
			{
				return this._em_fechanacimiento;
			}
			set
			{
				if ((this._em_fechanacimiento != value))
				{
					this._em_fechanacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string em_nombre
		{
			get
			{
				return this._em_nombre;
			}
			set
			{
				if ((this._em_nombre != value))
				{
					this._em_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_contrasena
		{
			get
			{
				return this._em_contrasena;
			}
			set
			{
				if ((this._em_contrasena != value))
				{
					this._em_contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_tipoid", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string em_tipoid
		{
			get
			{
				return this._em_tipoid;
			}
			set
			{
				if ((this._em_tipoid != value))
				{
					this._em_tipoid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_direccion
		{
			get
			{
				return this._em_direccion;
			}
			set
			{
				if ((this._em_direccion != value))
				{
					this._em_direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_cargo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_cargo
		{
			get
			{
				return this._em_cargo;
			}
			set
			{
				if ((this._em_cargo != value))
				{
					this._em_cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_contacto", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string em_contacto
		{
			get
			{
				return this._em_contacto;
			}
			set
			{
				if ((this._em_contacto != value))
				{
					this._em_contacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_fechaentrada", DbType="Date NOT NULL")]
		public System.DateTime em_fechaentrada
		{
			get
			{
				return this._em_fechaentrada;
			}
			set
			{
				if ((this._em_fechaentrada != value))
				{
					this._em_fechaentrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_estado
		{
			get
			{
				return this._em_estado;
			}
			set
			{
				if ((this._em_estado != value))
				{
					this._em_estado = value;
				}
			}
		}
	}
	
	public partial class listarEmpleadoResult
	{
		
		private string _em_tipoid;
		
		private string _em_identificacion;
		
		private string _em_nombre;
		
		private string _em_cargo;
		
		private string _em_contacto;
		
		private System.DateTime _em_fechanacimiento;
		
		private System.DateTime _em_fechaentrada;
		
		private string _em_estado;
		
		public listarEmpleadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_tipoid", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string em_tipoid
		{
			get
			{
				return this._em_tipoid;
			}
			set
			{
				if ((this._em_tipoid != value))
				{
					this._em_tipoid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_identificacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string em_identificacion
		{
			get
			{
				return this._em_identificacion;
			}
			set
			{
				if ((this._em_identificacion != value))
				{
					this._em_identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string em_nombre
		{
			get
			{
				return this._em_nombre;
			}
			set
			{
				if ((this._em_nombre != value))
				{
					this._em_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_cargo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_cargo
		{
			get
			{
				return this._em_cargo;
			}
			set
			{
				if ((this._em_cargo != value))
				{
					this._em_cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_contacto", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string em_contacto
		{
			get
			{
				return this._em_contacto;
			}
			set
			{
				if ((this._em_contacto != value))
				{
					this._em_contacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_fechanacimiento", DbType="Date NOT NULL")]
		public System.DateTime em_fechanacimiento
		{
			get
			{
				return this._em_fechanacimiento;
			}
			set
			{
				if ((this._em_fechanacimiento != value))
				{
					this._em_fechanacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_fechaentrada", DbType="Date NOT NULL")]
		public System.DateTime em_fechaentrada
		{
			get
			{
				return this._em_fechaentrada;
			}
			set
			{
				if ((this._em_fechaentrada != value))
				{
					this._em_fechaentrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_estado
		{
			get
			{
				return this._em_estado;
			}
			set
			{
				if ((this._em_estado != value))
				{
					this._em_estado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
